version: "3.3"
services:
    redis:
        image: redis
        ports:
           - "6379:6379"
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            - PORT=5000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - FLASK_APP=app.main
        ports:
            - "5000:5000"

    worker:
        build:
            context: ./
            dockerfile: Dockerfile
        command: rq worker --url redis://redis:6379

 
        
